from packages.hardware_contracts.models import RobotCommand

class CommandValidator:
    """
    Validates high-level intents generated by the LLM before passing to the hardware gateway.
    Ensures safety limits and rejects unsupported physical commands in the prototype phase.
    """
    
    ALLOWED_INTENTS = {"stop", "led_color", "celebrate"}
    
    @staticmethod
    def validate(command: RobotCommand) -> bool:
        if command.intent not in CommandValidator.ALLOWED_INTENTS:
            print(f"[SECURITY] Rejected LLM hardware command intent: {command.intent}")
            return False
            
        # Specific parameter validations can go here
        if command.intent == "led_color":
            color = command.parameters.get("color")
            if color not in ["red", "green", "blue", "yellow", "off"]:
                print(f"[SECURITY] Rejected invalid LED color: {color}")
                return False
                
        return True
